// <auto-generated />
// Generated by BuildInfoGenerator on 2025-09-08T19:27:47Z
public static class BuildInfo
{
    public const string BuildTimeUtc    = "2025-09-08T19:27:47Z";
    public const string Version         = "0.1";
    public const string ProductName     = "SmolbeanPlanet3D";
    public const string CompanyName     = "DanteLore";
    public const string UnityVersion    = "6000.1.12f1";
    public const string Platform        = "StandaloneLinux64";
    public const string ScriptingBackend= "Mono2x";
}