#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;

// This class ensures that a stub BuildInfo.g.cs file exists in the Editor.

[InitializeOnLoad]
public static class BuildInfoUnityEditor  
{
    static BuildInfoUnityEditor()
    {
        var filename = Path.Combine(Application.dataPath, "Scripts", "CI", "BuildInfo", "BuildInfo.g.cs");
        if (!File.Exists(filename))
        {
            File.WriteAllText(filename, @"// <auto-generated stub />
public static class BuildInfo
{
    public const string BuildTimeUtc     = ""EDITOR"";
    public const string Version          = """";
    public const string ProductName      = """";
    public const string CompanyName      = """";
    public const string UnityVersion     = """";
    public const string Platform         = ""Editor"";
    public const string ScriptingBackend = """";
}");
            AssetDatabase.ImportAsset(filename, ImportAssetOptions.ForceUpdate);
            Debug.Log("[BuildInfo] Created stub BuildInfo.g.cs for Editor.");
        }
    }
}
#endif
