#if UNITY_EDITOR
using System;
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;

/// <summary>
/// Writes Assets/Generated/BuildInfo.g.cs with compile-time constants.
/// Call BuildInfoGenerator.Generate(target) from your CI build code before BuildPipeline.BuildPlayer.
/// </summary>
public static class BuildInfoGenerator
{
    public static void Generate(BuildTarget target, string versionOverride = null, string productNameOverride = null)
    {
        var group = BuildPipeline.GetBuildTargetGroup(target);
        var named = NamedBuildTarget.FromBuildTargetGroup(group);
        var platform = target.ToString();
        var backend = PlayerSettings.GetScriptingBackend(named).ToString();
        var unityVersion = Application.unityVersion;
        var version = string.IsNullOrEmpty(versionOverride) ? PlayerSettings.bundleVersion : versionOverride;
        var productName = string.IsNullOrEmpty(productNameOverride) ? PlayerSettings.productName : productNameOverride;
        var companyName = PlayerSettings.companyName;
        var buildTimeUtc = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ");

        // Write file
        var filename = Path.Combine(Application.dataPath, "Scripts", "CI", "BuildInfo", "BuildInfo.g.cs");

        var source = $@"// <auto-generated />
// Generated by {nameof(BuildInfoGenerator)} on {buildTimeUtc}
public static class BuildInfo
{{
    public const string BuildTimeUtc    = ""{Esc(buildTimeUtc)}"";
    public const string Version         = ""{Esc(version)}"";
    public const string ProductName     = ""{Esc(productName)}"";
    public const string CompanyName     = ""{Esc(companyName)}"";
    public const string UnityVersion    = ""{Esc(unityVersion)}"";
    public const string Platform        = ""{Esc(platform)}"";
    public const string ScriptingBackend= ""{Esc(backend)}"";
}}";

        File.WriteAllText(filename, source);
        AssetDatabase.ImportAsset(filename, ImportAssetOptions.ForceUpdate);
        Debug.Log($"[BuildInfo] Wrote {filename} for {platform} ({backend}) v{version}");
    }

    private static string Esc(string s) =>
        (s ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
}
#endif